import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import NavBar from "./navbar";
import SideBar from "./sidebar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  // post,
  // title,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="flex">
          <NavBar />
        </div>
        <div className="flex">
          <SideBar />
          <div className="flex justify-items-center">
          {children}
          </div>
 
        </div>

      </body>
    </html>
  );
}
